baseURL = 'https://chalk-hugo-demo.onrender.com/'
languageCode = 'en-us'
title = 'Chalk theme ported to Hugo'
theme= 'chalk'
enableEmoji = true

[params]
[params.chalk]
  # chalk theme parameters
  about_enabled = true # Change to true if you wish to show an icon in the navigation that redirects to the about page
  scrollappear_enabled = true
  theme_toggle = true
  rss_enabled = true
  blog_theme = 'light' # Doesn't matter if theme_toggle = true
  local_fonts = false

[params.social]
  # social network accounts
  github = 'ph-ph'
